export const gaEvent = {
  GET_VIDEO_START: "GET_VIDEO_START",
  GET_VIDEO_SUSCCESS: "GET_VIDEO_SUCCESS",
  GET_VIDEO_FAILED: "GET_VIDEO_FAILED",
  DOWNLOAD_VIDEO_SUCCESS: "DOWNLOAD_VIDEO_SUCCESS",
  DOWNLOAD_VIDEO_FAILED: "DOWNLOAD_VIDEO_FAILED",
  DOWNLOAD_ALL_VIDEOS_SUCCESS: "DOWNLOAD_ALL_VIDEOS_SUCCESS",
  DOWNLOAD_ALL_VIDEOS_FAILED: "DOWNLOAD_ALL_VIDEOS_FAILED",
};
