import LayoutMain from "@/components/layout/LayoutMain";

export default function PrivacyPolicy() {
  return (
    <LayoutMain
      meta={{
        title: "Privacy Policy - TikNotes.App",
        description:
          "Learn how TikNotes.App protects your data and privacy. Our policy outlines information collection, usage, and security measures to ensure a safe user experience.",
      }}
    >
      <div className="content">
        <h1>Privacy Policy</h1>
        <p>
          <span className="font-medium">Last updated:</span>{" "}
          <span className="text-slate-500">September 18, 2024</span>
        </p>
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2>Interpretation and Definitions</h2>

        <h3>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3>Definitions</h3>
        <div>
          For the purposes of this Privacy Policy:
          <ul className="list-disc">
            <li>
              <b>Account</b> means a unique account created for You to access
              our Service or parts of our Service.
            </li>
            <li>
              <b>Company</b> (referred to as either &quot;the Company&quot;,
              &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this
              Agreement) refers to TikNotes.App.
            </li>
            <li>
              <b>Cookies</b> are small files that are placed on Your computer,
              mobile device or any other device by a website, containing the
              details of Your browsing history on that website among its many
              uses
            </li>
            <li>
              <b>Device</b> means any device that can access the Service such as
              a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <b>Personal Data</b> is any information that relates to an
              identified or identifiable individual. Service refers to the
              Website.
            </li>
            <li>
              <b>Service</b> refers to the Website.
            </li>
            <li>
              <b>Service Provider</b> means any natural or legal person who
              processes the data on behalf of the Company. It refers to
              third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <b>Usage Data</b> refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <b>Website</b> refers to TikNotes.App, accessible from
              tiknotes.app
            </li>
            <li>
              <b>You</b> means the individual accessing or using the Service, or
              the company, or other legal entity on behalf of which such
              individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </div>

        <h2>Collecting and Using Your Personal Data</h2>
      </div>
    </LayoutMain>
  );
}
